import type { DocumentSlot } from './types';

export const documentSlots: DocumentSlot[] = [
    {
        id: 'slot-aadhaar',
        typeCode: 'aadhaar',
        typeName: 'Aadhaar Card',
        category: 'identity',
        required: true,
        maxSizeMB: 5,
        allowedFormats: ['pdf', 'jpg', 'png'],
        instructions: 'Upload clear scan of both sides of Aadhaar card',
    },
    {
        id: 'slot-pan',
        typeCode: 'pan',
        typeName: 'PAN Card',
        category: 'identity',
        required: false,
        maxSizeMB: 5,
        allowedFormats: ['pdf', 'jpg', 'png'],
        instructions: 'Upload clear scan of PAN card (if available)',
    },
    {
        id: 'slot-photo',
        typeCode: 'passport_photo',
        typeName: 'Passport Photo',
        category: 'identity',
        required: true,
        maxSizeMB: 2,
        allowedFormats: ['jpg', 'png'],
        instructions: 'Recent passport-size photo with white background',
    },
    {
        id: 'slot-class10',
        typeCode: 'class_10_marksheet',
        typeName: 'Class 10 Marksheet',
        category: 'academic',
        required: true,
        maxSizeMB: 5,
        allowedFormats: ['pdf'],
        instructions: 'Original marksheet from board examination',
    },
    {
        id: 'slot-class12',
        typeCode: 'class_12_marksheet',
        typeName: 'Class 12 Marksheet',
        category: 'academic',
        required: true,
        maxSizeMB: 5,
        allowedFormats: ['pdf'],
        instructions: 'Original marksheet from board examination',
    },
    {
        id: 'slot-neet-scorecard',
        typeCode: 'neet_scorecard',
        typeName: 'NEET Scorecard',
        category: 'eligibility',
        required: true,
        maxSizeMB: 5,
        allowedFormats: ['pdf'],
        instructions: 'Official NEET UG scorecard from NTA',
    },
    {
        id: 'slot-neet-admit',
        typeCode: 'neet_admit_card',
        typeName: 'NEET Admit Card',
        category: 'eligibility',
        required: true,
        maxSizeMB: 5,
        allowedFormats: ['pdf'],
        instructions: 'NEET UG admit card with photograph',
    },
    {
        id: 'slot-domicile',
        typeCode: 'domicile_certificate',
        typeName: 'Domicile Certificate',
        category: 'eligibility',
        required: true,
        maxSizeMB: 5,
        allowedFormats: ['pdf'],
        instructions: 'State domicile certificate (required for state quota)',
    },
    {
        id: 'slot-caste',
        typeCode: 'caste_certificate',
        typeName: 'Caste Certificate',
        category: 'eligibility',
        required: false,
        maxSizeMB: 5,
        allowedFormats: ['pdf'],
        instructions: 'Required only for reserved category candidates',
    },
    {
        id: 'slot-income',
        typeCode: 'income_certificate',
        typeName: 'Income Certificate',
        category: 'financial',
        required: false,
        maxSizeMB: 5,
        allowedFormats: ['pdf'],
        instructions: 'Required for EWS and scholarship applications',
    },
    {
        id: 'slot-tc',
        typeCode: 'transfer_certificate',
        typeName: 'Transfer Certificate',
        category: 'academic',
        required: true,
        maxSizeMB: 5,
        allowedFormats: ['pdf'],
        instructions: 'TC from last attended institution',
    },
    {
        id: 'slot-migration',
        typeCode: 'migration_certificate',
        typeName: 'Migration Certificate',
        category: 'academic',
        required: false,
        maxSizeMB: 5,
        allowedFormats: ['pdf'],
        instructions: 'Required for students from other states/boards',
    },
    {
        id: 'slot-medical',
        typeCode: 'medical_fitness',
        typeName: 'Medical Fitness Certificate',
        category: 'medical',
        required: true,
        maxSizeMB: 5,
        allowedFormats: ['pdf'],
        instructions: 'Recent medical fitness certificate from registered practitioner',
    },
    {
        id: 'slot-gap',
        typeCode: 'gap_certificate',
        typeName: 'Gap Certificate',
        category: 'academic',
        required: false,
        maxSizeMB: 5,
        allowedFormats: ['pdf'],
        instructions: 'Required if there is a gap in education',
    },
];

export const getSlotsByCategory = (category: string) =>
    documentSlots.filter(slot => slot.category === category);

export const getRequiredSlots = () =>
    documentSlots.filter(slot => slot.required);

export default documentSlots;
