import type { AuditLog, ConsentRecord, DataRetentionPolicy } from './types';

export const mockAuditLogs: AuditLog[] = [
    {
        id: 'AUD001',
        timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
        userId: 'ADM001',
        userName: 'Super Admin',
        userRole: 'admin',
        action: 'view_pii',
        resource: 'student',
        resourceId: 'ST20260001',
        details: 'Viewed full Aadhaar number for verification',
        ipAddress: '192.168.1.100',
        success: true,
        riskLevel: 'medium',
    },
    {
        id: 'AUD002',
        timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        userId: 'STF002',
        userName: 'Rahul Verma',
        userRole: 'staff',
        action: 'verify_document',
        resource: 'document',
        resourceId: 'DOC-AADHAAR-001',
        details: 'Verified Aadhaar card for student ST20260005',
        ipAddress: '192.168.1.101',
        success: true,
        riskLevel: 'low',
    },
    {
        id: 'AUD003',
        timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        userId: 'ADM001',
        userName: 'Super Admin',
        userRole: 'admin',
        action: 'export_data',
        resource: 'report',
        resourceId: 'RPT-2026-01',
        details: 'Exported student list to Excel (250 records)',
        ipAddress: '192.168.1.100',
        success: true,
        riskLevel: 'high',
    },
    {
        id: 'AUD004',
        timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
        userId: 'STF001',
        userName: 'Priya Sharma',
        userRole: 'staff',
        action: 'payment_processed',
        resource: 'payment',
        resourceId: 'PAY-001',
        details: 'Processed tuition payment of ₹65,000',
        ipAddress: '192.168.1.102',
        success: true,
        riskLevel: 'medium',
    },
    {
        id: 'AUD005',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        userId: 'ST20260001',
        userName: 'Aditya Sharma',
        userRole: 'student',
        action: 'consent_updated',
        resource: 'consent',
        resourceId: 'CON-001',
        details: 'Granted consent for third-party data sharing',
        ipAddress: '203.122.45.67',
        success: true,
        riskLevel: 'low',
    },
];

export const mockConsentRecords: ConsentRecord[] = [
    {
        id: 'CON001',
        userId: 'ST20260001',
        userName: 'Aditya Sharma',
        type: 'data_processing',
        status: 'granted',
        version: '1.2',
        grantedAt: '2026-01-02T10:30:00Z',
        expiresAt: '2027-01-02T10:30:00Z',
    },
    {
        id: 'CON002',
        userId: 'ST20260001',
        userName: 'Aditya Sharma',
        type: 'marketing',
        status: 'denied',
        version: '1.2',
    },
    {
        id: 'CON003',
        userId: 'ST20260001',
        userName: 'Aditya Sharma',
        type: 'third_party_sharing',
        status: 'granted',
        version: '1.1',
        grantedAt: '2026-01-02T10:30:00Z',
        expiresAt: '2027-01-02T10:30:00Z',
    },
    {
        id: 'CON004',
        userId: 'ST20260001',
        userName: 'Aditya Sharma',
        type: 'sensitive_personal_data',
        status: 'granted',
        version: '1.0',
        grantedAt: '2026-01-02T10:30:00Z',
        expiresAt: '2027-01-02T10:30:00Z',
    },
];

export const dataRetentionPolicies: DataRetentionPolicy[] = [
    {
        id: 'RET001',
        dataType: 'Audit Logs',
        retentionPeriodDays: 365,
        autoDeleteEnabled: true,
        lastRunAt: '2026-01-01T00:00:00Z',
        nextRunAt: '2026-02-01T00:00:00Z',
        recordsProcessed: 1250,
    },
    {
        id: 'RET002',
        dataType: 'Session Data',
        retentionPeriodDays: 30,
        autoDeleteEnabled: true,
        lastRunAt: '2026-01-15T00:00:00Z',
        nextRunAt: '2026-01-22T00:00:00Z',
        recordsProcessed: 5420,
    },
    {
        id: 'RET003',
        dataType: 'Inactive Student Records',
        retentionPeriodDays: 730,
        autoDeleteEnabled: false,
    },
];

const mockData = { mockAuditLogs, mockConsentRecords, dataRetentionPolicies };
export default mockData;
