import type { Agent, Referral, Commission } from './types';

export const mockAgents: Agent[] = [
    {
        id: 'AG001',
        name: 'Rajesh Kumar',
        email: 'rajesh.kumar@globalmed.com',
        phone: '+91 99887 76655',
        status: 'active',
        registeredAt: '2024-06-15',
        zone: 'South Maharashtra',
        city: 'Latur',
        state: 'Maharashtra',
        panNumber: 'ABCDE1234F',
        bankDetails: {
            accountNumber: '123456789012',
            ifsc: 'SBIN0001234',
            bankName: 'State Bank of India',
            accountHolder: 'Rajesh Kumar',
        },
        stats: {
            totalReferrals: 45,
            activeStudents: 28,
            conversions: 22,
            totalEarnings: 220000,
            pendingCommissions: 40000,
        },
    },
    {
        id: 'AG002',
        name: 'Anita Deshpande',
        email: 'anita@eliteadmissions.com',
        phone: '+91 88776 65544',
        status: 'active',
        registeredAt: '2024-08-20',
        zone: 'West Maharashtra',
        city: 'Pune',
        state: 'Maharashtra',
        stats: {
            totalReferrals: 32,
            activeStudents: 18,
            conversions: 15,
            totalEarnings: 150000,
            pendingCommissions: 25000,
        },
    },
    {
        id: 'AG003',
        name: 'Suresh Patil',
        email: 'suresh.patil@medconsult.in',
        phone: '+91 77665 54433',
        status: 'active',
        registeredAt: '2025-01-10',
        zone: 'North Karnataka',
        city: 'Hubli',
        state: 'Karnataka',
        stats: {
            totalReferrals: 18,
            activeStudents: 12,
            conversions: 8,
            totalEarnings: 80000,
            pendingCommissions: 15000,
        },
    },
    {
        id: 'AG004',
        name: 'Priya Menon',
        email: 'priya.menon@careerpath.in',
        phone: '+91 99001 12233',
        status: 'pending_verification',
        registeredAt: '2026-01-05',
        zone: 'Kerala',
        city: 'Kochi',
        state: 'Kerala',
        stats: {
            totalReferrals: 5,
            activeStudents: 5,
            conversions: 0,
            totalEarnings: 0,
            pendingCommissions: 0,
        },
    },
];

export const mockReferrals: Referral[] = [
    {
        id: 'REF001',
        agentId: 'AG001',
        studentId: 'ST20260001',
        studentName: 'Aditya Sharma',
        referredAt: '2026-01-02',
        status: 'enrolled',
        currentStage: 'enrollment',
        college: 'Government Medical College, Nagpur',
        commissionEligible: true,
    },
    {
        id: 'REF002',
        agentId: 'AG001',
        studentId: 'ST20260006',
        studentName: 'Shivam Patel',
        referredAt: '2026-01-05',
        status: 'active',
        currentStage: 'counseling',
        commissionEligible: false,
    },
    {
        id: 'REF003',
        agentId: 'AG002',
        studentId: 'ST20260011',
        studentName: 'Kunal Kulkarni',
        referredAt: '2026-01-08',
        status: 'enrolled',
        currentStage: 'enrollment',
        college: 'B.J. Medical College, Pune',
        commissionEligible: true,
    },
];

export const mockCommissions: Commission[] = [
    {
        id: 'COM001',
        agentId: 'AG001',
        referralId: 'REF001',
        studentId: 'ST20260001',
        studentName: 'Aditya Sharma',
        amount: 10000,
        status: 'paid',
        createdAt: '2026-01-10',
        approvedAt: '2026-01-12',
        approvedBy: 'ADM001',
        paidAt: '2026-01-15',
        transactionId: 'TXN20260115001',
    },
    {
        id: 'COM002',
        agentId: 'AG002',
        referralId: 'REF003',
        studentId: 'ST20260011',
        studentName: 'Kunal Kulkarni',
        amount: 10000,
        status: 'approved',
        createdAt: '2026-01-12',
        approvedAt: '2026-01-14',
        approvedBy: 'ADM001',
    },
    {
        id: 'COM003',
        agentId: 'AG001',
        referralId: 'REF002',
        studentId: 'ST20260006',
        studentName: 'Shivam Patel',
        amount: 10000,
        status: 'pending',
        createdAt: '2026-01-15',
        remarks: 'Pending student enrollment confirmation',
    },
];

const mockData = { mockAgents, mockReferrals, mockCommissions };
export default mockData;
