"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { DataTable, DataTableColumn } from "@/components/ui/data-table"
import {
    FileText, Download, Calendar, BarChart3, FileSpreadsheet
} from "lucide-react"

interface ReportLogEntry {
    [key: string]: string | number;
    id: string;
    reportName: string;
    type: string;
    generatedBy: string;
    generatedAt: string;
    recordCount: number;
    status: string;
    fileSize: string;
}

const mockReportLogs: ReportLogEntry[] = [
    {
        id: 'RPT001',
        reportName: 'Student Enrollment Summary',
        type: 'enrollment',
        generatedBy: 'Admin',
        generatedAt: '2026-01-19 10:30:00',
        recordCount: 1245,
        status: 'completed',
        fileSize: '2.4 MB',
    },
    {
        id: 'RPT002',
        reportName: 'Category-wise Distribution',
        type: 'analytics',
        generatedBy: 'Staff',
        generatedAt: '2026-01-19 09:15:00',
        recordCount: 856,
        status: 'completed',
        fileSize: '1.8 MB',
    },
    {
        id: 'RPT003',
        reportName: 'Payment Collection Report',
        type: 'payment',
        generatedBy: 'Admin',
        generatedAt: '2026-01-18 16:45:00',
        recordCount: 432,
        status: 'completed',
        fileSize: '890 KB',
    },
    {
        id: 'RPT004',
        reportName: 'Branch Performance Metrics',
        type: 'analytics',
        generatedBy: 'Admin',
        generatedAt: '2026-01-18 14:20:00',
        recordCount: 12,
        status: 'completed',
        fileSize: '450 KB',
    },
    {
        id: 'RPT005',
        reportName: 'Document Verification Status',
        type: 'compliance',
        generatedBy: 'Staff',
        generatedAt: '2026-01-18 11:00:00',
        recordCount: 678,
        status: 'completed',
        fileSize: '1.2 MB',
    },
    {
        id: 'RPT006',
        reportName: 'Counseling Progress Report',
        type: 'counseling',
        generatedBy: 'Admin',
        generatedAt: '2026-01-17 17:30:00',
        recordCount: 234,
        status: 'completed',
        fileSize: '560 KB',
    },
];

const typeColors: Record<string, string> = {
    enrollment: 'bg-blue-500',
    analytics: 'bg-purple-500',
    payment: 'bg-green-500',
    compliance: 'bg-orange-500',
    counseling: 'bg-pink-500',
};

const columns: DataTableColumn<ReportLogEntry>[] = [
    {
        key: 'id',
        header: 'Report ID',
        sortable: true,
        render: (value) => (
            <span className="font-mono text-xs font-bold">{String(value)}</span>
        ),
    },
    {
        key: 'reportName',
        header: 'Report Name',
        sortable: true,
        filterable: true,
        render: (value) => (
            <span className="font-medium">{String(value)}</span>
        ),
    },
    {
        key: 'type',
        header: 'Type',
        sortable: true,
        filterable: true,
        filterType: 'select',
        filterOptions: [
            { label: 'Enrollment', value: 'enrollment' },
            { label: 'Analytics', value: 'analytics' },
            { label: 'Payment', value: 'payment' },
            { label: 'Compliance', value: 'compliance' },
            { label: 'Counseling', value: 'counseling' },
        ],
        render: (value) => (
            <Badge className={`text-[10px] ${typeColors[String(value)] || 'bg-gray-500'}`}>
                {String(value)}
            </Badge>
        ),
    },
    {
        key: 'generatedBy',
        header: 'Generated By',
        sortable: true,
    },
    {
        key: 'generatedAt',
        header: 'Date',
        sortable: true,
        render: (value) => (
            <span className="text-xs">{String(value)}</span>
        ),
    },
    {
        key: 'recordCount',
        header: 'Records',
        sortable: true,
        render: (value) => (
            <span className="font-mono">{Number(value).toLocaleString()}</span>
        ),
    },
    {
        key: 'fileSize',
        header: 'Size',
        render: (value) => (
            <span className="text-xs text-muted-foreground">{String(value)}</span>
        ),
    },
    {
        key: 'status',
        header: 'Status',
        render: (value) => (
            <Badge variant="outline" className="text-[10px] text-green-500 border-green-500/30">
                {String(value)}
            </Badge>
        ),
    },
];

export default function AdminReportsPage() {
    return (
        <div className="space-y-6 p-6">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div className="space-y-1">
                    <div className="flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary w-fit border border-primary/20">
                        <FileText className="h-3 w-3" />
                        <span className="text-[10px] font-bold uppercase tracking-[0.1em]">Report Center</span>
                    </div>
                    <h1 className="text-2xl font-black tracking-tight">Reports & Analytics</h1>
                    <p className="text-sm text-muted-foreground">
                        Generate, view, and download reports across all branches
                    </p>
                </div>
                <div className="flex items-center gap-3">
                    <Button variant="outline" size="sm">
                        <Calendar className="h-4 w-4 mr-2" />
                        Schedule
                    </Button>
                    <Button size="sm">
                        <FileSpreadsheet className="h-4 w-4 mr-2" />
                        New Report
                    </Button>
                </div>
            </div>

            {/* Quick Stats */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <Card className="glass-card">
                    <CardContent className="pt-6">
                        <div className="flex items-center justify-between">
                            <div>
                                <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
                                    Reports Generated
                                </p>
                                <p className="text-2xl font-black">{mockReportLogs.length}</p>
                            </div>
                            <FileText className="h-8 w-8 text-primary/30" />
                        </div>
                    </CardContent>
                </Card>
                <Card className="glass-card">
                    <CardContent className="pt-6">
                        <div className="flex items-center justify-between">
                            <div>
                                <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
                                    Total Records
                                </p>
                                <p className="text-2xl font-black text-blue-500">
                                    {mockReportLogs.reduce((sum, r) => sum + r.recordCount, 0).toLocaleString()}
                                </p>
                            </div>
                            <BarChart3 className="h-8 w-8 text-blue-500/30" />
                        </div>
                    </CardContent>
                </Card>
                <Card className="glass-card">
                    <CardContent className="pt-6">
                        <div className="flex items-center justify-between">
                            <div>
                                <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
                                    Analytics Reports
                                </p>
                                <p className="text-2xl font-black text-purple-500">
                                    {mockReportLogs.filter(r => r.type === 'analytics').length}
                                </p>
                            </div>
                        </div>
                    </CardContent>
                </Card>
                <Card className="glass-card">
                    <CardContent className="pt-6">
                        <div className="flex items-center justify-between">
                            <div>
                                <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
                                    This Week
                                </p>
                                <p className="text-2xl font-black text-green-500">4</p>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </div>

            {/* Report Logs Table */}
            <Card className="glass-card">
                <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                        <FileText className="h-5 w-5 text-primary" />
                        Recent Reports
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    <DataTable
                        data={mockReportLogs}
                        columns={columns}
                        keyField="id"
                        searchable
                        actions={[
                            {
                                label: 'Download',
                                icon: Download,
                                onClick: (row) => console.log('Download:', row.id),
                            },
                        ]}
                        onRefresh={() => console.log('Refresh')}
                        onExport={() => console.log('Export all')}
                        pageSize={10}
                    />
                </CardContent>
            </Card>
        </div>
    )
}
